### PR TITLE
Fix build of example with latest lxqt-build-tools

### PR DESCRIPTION
**Pull request by yan12125**
Latest lxqt-build-tools disables foreach. Fix it.

Test: build qtermwidget with ```-DBUILD_EXAMPLE=ON```

### CODE REVIEW

**Comment by yan12125** [comment]
Hi @luis-pereira, as you are an expert in this area, could you have a look?

**Comment by luis-pereira** [comment]
This is my fault. Didn't build the example.

**Comment by yan12125** [comment]
Thanks for the suggestion. Is there a way to detect possible detaching (compiler flags, static analyzers, runtime checkers, ...)?

And I wonder if it makes sense to build the example by default.

**Comment by luis-pereira** [comment]
@yan12125 IMO the example should not be in the default build.
I recommend [clazy](https://github.com/KDE/clazy/). It allows provides compile-time warnings about qt best practices.
For range for detachments: anything that uses `containter.begin() / container.end()` instead of `container.cbegin() / container.cend()` can produce a detach.

p.s. Maybe you could squash the two commits.

**Comment by yan12125** [comment]
Thanks for the info. I'll have a look at clazy.

> p.s. Maybe you could squash the two commits.

Done!

**Pull request merged**
