### PR TITLE
Display wide characters correctly (Part I)

### PR DESCRIPTION
**Pull request by yan12125**
The ancient `konsole_wcwidth` can't recognize some double-width characters. For example, copy and paste the string `《別來無恙》` into bash, and move cursors around with left arrow, right arrow, Home and End keys. The current line becomes a mess. My patch fixes this problem.

The story doesn't end here. For example, if I paste `𝕐` into the shell, things are even worse. That's because QTerminal assume characters to be UCS-2, so it cannot handle characters outside the Basic Multilingual Plane correctly. I'd like to leave this problem into the next pull request.

By the way, is git submodule a good idea for external dependencies? This version looks the most promising, as it declares to be "Unicode 9-conformant", and is used in Termux, one of the most popular terminal emulators on Android.

### CODE REVIEW

**Comment by agaida** [comment]
@yan12125 - hmm, i would prevent submodules wherever i could in the real development process (bitten one time to much) - but submodules are generally a nice way to get the current code of something if one know about the pitfalls - if not one will learn them very fast.

**Comment by agaida** [comment]
thats not sufficient

**Comment by yan12125** [comment]
I'll wait for some to see whether people at Termux are serious to their fork or not. If I get no response I'll try to update  Markus Kuhn's version to Unicode 9.0.

**Comment by yan12125** [comment]
Hello @agaida, a Termux member has added a MIT license declaration in https://github.com/termux/wcwidth/commit/aae37538d371f45ae3d834bd33cad6807b0e6b35. Is it good to move on?

**Comment by agaida** [comment]
nearly ok i think - to be honest i would only copy both files ( w*.c and .h) and integrate it. However, the *.c and *.h files should contain a license header - you could help them with that, a PR is no rocket science. With the headers in place no objections. But pleae leave out the sub-modules.

**Comment by yan12125** [comment]
Another upstream update: https://github.com/termux/wcwidth/commit/d48cb1eca970f3d2971ae7cddfb375dc866ee714. I guess that looks good now?

**Comment by agaida** [comment]
yes - but i'm still not ok with the git submodule.

**Comment by yan12125** [comment]
Force pushed. I have some modifications to termux's version. Changes can be found in my fork: https://github.com/yan12125/wcwidth/commits/master

**Comment by yan12125** [comment]
I decide to use a better maintained library instead of termux/wcwidth => #99. @agaida Sorry for bothering you with an awful project

**Comment by agaida** [comment]
exactly the opposite - sorry for being pain in the ass. Glad you found a better solution. Thank you very much.

**Pull request closed without merging**
