### PR TITLE
Other box drawing characters

### PR DESCRIPTION
**Pull request by yan12125**
Porting of a KDE fix https://github.com/KDE/konsole/commit/1a61aaa5915b5c4a5b205e87d35c38562f932fe0

Fixes https://github.com/lxde/qterminal/issues/277

Depends on #94 and #96

### CODE REVIEW

**Comment by agaida** [comment]
@yan12125 - i think this PR needs a overahaul because of: ￼	Replace the ancient wcwidth impl. with Termux's fork

**Comment by yan12125** [comment]
Yes - I'd like to wait for #99 first.

**Comment by agaida** [comment]
@yan12125 - ok, here we go

**Comment by yan12125** [comment]
Re-pushed. Now #96 depends on this one instead.

**Comment by agaida** [comment]
GTM

**Pull request merged**
