### PR TITLE
Backport the default.keytab from Konsole

### LINKED ISSUE #103: Arrow keys don't work
In the example program (or using QTermWidget in any application) the left, right, down and up arrows do nothing. This is quite limiting as it makes scrollback and command editing unavailable. 

I am compiling the latest release (0.7.0) against Qt 5.6 on Ubuntu 14.04

Note: I believe this has something to do with event filters, but I don't know enough Qt programming to fix it

### PR DESCRIPTION
**Pull request by DonnieWest**
Fixes #103 and #43

### CODE REVIEW

**Comment by yan12125** [comment]
For (Prior, Next) => (PgUp, PgDown), I'm curious why the original keys are broken, as [prior and next are aliases of PgUp and PgDown, respectively](https://github.com/lxde/qtermwidget/blob/ef45142/lib/KeyboardTranslator.cpp#L453-L457). It's fine to stay away from ancient workarounds, but please change all *.keytab files.

---

In #103:

> I've fixed it for my environment by adding the escape codes to the default.keytab file

This fix looks reasonable. Could you give an example usage requiring this fix? I'd like to test it.

**Comment by DonnieWest** [comment]
@yan12125 I can get all the *.keytab files backported as well

In regards to #103 I use tmux as my terminal multiplexer and I use Left + Shift and Right + Shift to move between panes. Currently, these escape codes aren't being passed down to tmux and so these sequences are ignored.

To test it in your own tmux config, you can add these lines
```
bind -n S-left prev
bind -n S-right next
```

A complete example can be found [here in my dotfiles](https://raw.githubusercontent.com/DonnieWest/dotfiles/dotfiles/.tmux.conf)

**Comment by DonnieWest** [comment]
@yan12125 Updated all *.keytab files for consistency. Please let me know how that looks :)

**Comment by DonnieWest** [comment]
@yan12125 any word on this PR? Anything I should fixup?

**Comment by DonnieWest** [comment]
@yan12125 any word here? Anything I should fix?

**Comment by yan12125** [comment]
Sorry, in my memory I asked for making identation consistent (put colons in the same column) but apparently there was something wrong in my head :(

**Comment by DonnieWest** [comment]
It's fine. I'll get that fixed up shortly :)

**Comment by agaida** [comment]
nice

**Comment by DonnieWest** [comment]
This should be indented properly. After this is approved I can rebase :)

**Comment by yan12125** [comment]
Could you indent key tokens (```+Shift-AppScreen```, etc.) as well and squash commits?

**Comment by DonnieWest** [comment]
@yan12125 indented and squashed :)

**Comment by yan12125** [comment]
Thanks!

**Pull request merged**
