### PR TITLE
Use absolute paths for the library path

### PR DESCRIPTION
**Pull request by yan12125**
This fixes building in custom locations

Fixes lxde/qterminal#295

Here are two possible fixes:

1. link_directories. CMake recommends against it: https://cmake.org/cmake/help/v3.0/command/link_directories.html
2. Use find_library(), as recommended in the page mentioned above

Here I choose the second approach.

### CODE REVIEW

**Comment by luis-pereira** [comment]
@yan12125 The CMake stuff needs a complete update. We should the Targets way.
I'm already on it.

**Comment by yan12125** [comment]
> I'm already on it.

I guess you were referring to #120?

**Comment by luis-pereira** [comment]
@yan12125 Precisely. It will supersede this PR.

**Comment by yan12125** [comment]
Got it. That looks much better.

**Pull request closed without merging**
