### PR TITLE
Cmake maint

### PR DESCRIPTION
**Pull request by luis-pereira**
This PR will bring QTermWidget5 to a simple usage:

``` CMake
find_package(QTermWidget5 REQUIRED)
target_link_libraries(foo
    QTermWidget5
)
```

### CODE REVIEW

**Comment by yan12125** [comment]
Working fine with lxde/qterminal#303. Is it considered done?

**Comment by luis-pereira** [comment]
@yan12125 This one yes. But, now that I'm on it, I still have stuff to do in https://github.com/lxde/qterminal/pull/303.

**Comment by yan12125** [comment]
Thanks got it!

**Comment by luis-pereira** [comment]
@yan12125 Just found a mistake... in the translation stuff.

**Comment by luis-pereira** [comment]
Commit https://github.com/lxde/qtermwidget/commit/1847cc6e6a4413dc729870cb064e173f29303106 updated.

**Comment by luis-pereira** [comment]
@yan12125 Done. Pls test

**Comment by yan12125** [comment]
Here are two minor issues:
1. The example application doesn't build for in-tree builds:
```
[ 98%] Linking CXX executable example
/usr/bin/cmake -E cmake_link_script CMakeFiles/example.dir/link.txt --verbose=1
/usr/bin/c++    -fno-exceptions -Wall -Wextra -Wchar-subscripts -Wno-long-long -Wpointer-arith -Wundef -Wformat-security -Wnon-virtual-dtor -Woverloaded-virtual -Wpedantic -std=c++11 -g  -Wl,-Bsymbolic-functions -Wl,-Bsymbolic  CMakeFiles/example.dir/example/main.cpp.o  -o example -Wl,-rpath,/home/yen/Projects/qtermwidget -rdynamic libqtermwidget5.so.0.7.1 /usr/lib/libQt5Widgets.so.5.8.0 /usr/lib/libQt5Gui.so.5.8.0 /usr/lib/libQt5Core.so.5.8.0 -lutf8proc 
/usr/bin/ld: cannot open output file example: Is a directory
```
2. Duplicated installation calls for files in ```lib64/```: (see the last 3 lines)
```
$ make install
[100%] Built target qtermwidget5
Install the project...
-- Install configuration: "Debug"
-- Installing: /home/yen/usr/share/qtermwidget5/translations/qtermwidget_zh_TW.qm
-- Installing: /home/yen/usr/share/cmake/qtermwidget5/qtermwidget5-config-version.cmake
-- Installing: /home/yen/usr/share/cmake/qtermwidget5/qtermwidget5-targets.cmake
-- Installing: /home/yen/usr/share/cmake/qtermwidget5/qtermwidget5-targets-debug.cmake
-- Installing: /home/yen/usr/lib64/libqtermwidget5.so.0.7.1
-- Installing: /home/yen/usr/lib64/libqtermwidget5.so.0
-- Installing: /home/yen/usr/lib64/libqtermwidget5.so
-- Installing: /home/yen/usr/include/qtermwidget5/qtermwidget.h
-- Installing: /home/yen/usr/include/qtermwidget5/Filter.h
-- Installing: /home/yen/usr/include/qtermwidget5/qtermwidget_export.h
-- Installing: /home/yen/usr/share/qtermwidget5/kb-layouts
-- Installing: /home/yen/usr/share/qtermwidget5/kb-layouts/vt420pc.keytab
-- Installing: /home/yen/usr/share/qtermwidget5/kb-layouts/linux.keytab
-- Installing: /home/yen/usr/share/qtermwidget5/kb-layouts/solaris.keytab
-- Installing: /home/yen/usr/share/qtermwidget5/kb-layouts/macbook.keytab
-- Installing: /home/yen/usr/share/qtermwidget5/kb-layouts/historic
-- Installing: /home/yen/usr/share/qtermwidget5/kb-layouts/historic/x11r5.keytab
-- Installing: /home/yen/usr/share/qtermwidget5/kb-layouts/historic/vt100.keytab
-- Installing: /home/yen/usr/share/qtermwidget5/kb-layouts/default.keytab
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/Solarized.colorscheme
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/GreenOnBlack.colorscheme
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/SolarizedLight.colorscheme
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/BreezeModified.colorscheme
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/BlackOnRandomLight.colorscheme
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/Linux.colorscheme
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/WhiteOnBlack.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/BlackOnWhite.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/BlackOnLightYellow.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/DarkPastels.colorscheme
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/Transparent_lightbg.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/Transparent_MC.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/BlackOnLightColor.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/Transparent_darkbg.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/LightPicture.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/XTerm.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/Linux.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/Transparent.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/syscolor.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/GreenOnBlack.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/GreenTint_MC.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/DarkPicture.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/GreenTint.schema
-- Installing: /home/yen/usr/share/qtermwidget5/color-schemes/historic/vim.schema
-- Installing: /home/yen/usr/lib64/pkgconfig/qtermwidget5.pc
-- Installing: /home/yen/usr/share/cmake/qtermwidget5/qtermwidget5-config.cmake
-- Up-to-date: /home/yen/usr/lib64/libqtermwidget5.so.0.7.1
-- Up-to-date: /home/yen/usr/lib64/libqtermwidget5.so.0
-- Up-to-date: /home/yen/usr/lib64/libqtermwidget5.so
```

Other things look great! (Actually I don't understand most CMake stuffs. You're definitely an expert.)

**Comment by luis-pereira** [comment]
@yan12125 Actually I did not add support for in tree builds...

**Comment by luis-pereira** [comment]
@yan12125 Issue number 2 is fixed.

**Comment by luis-pereira** [comment]
@yan12125 Added superbuild support. Needs https://github.com/lxde/lxqt-build-tools/pull/19.

**Comment by yan12125** [comment]
It's reasonable to support out-of-source builds only. Do you think it's a good idea to prohibit in-tree builds? Neovim provides a useful module for that: https://github.com/neovim/neovim/blob/039c7ab/CMakeLists.txt#L12, https://github.com/neovim/neovim/blob/53eddb8/cmake/PreventInTreeBuilds.cmake

**Comment by luis-pereira** [comment]
@yan12125 I don't think it's necessary. Anybody that uses CMake knows (IMO) that it's a out of source build system. We don't prevent anywhere in LXQt and we never had issues with that AFAIK.
The superbuild mode that I'm referring to it's building all LXQt and then install LXQt at once.

**Comment by yan12125** [comment]
Thanks for those fixes and improvements!

**Pull request merged**
